### ISSUE TITLE
Load Data From Database Using TestID

### ISSUE THREAD

**Issue by hannahb1024** [hannahb1024/uob-sepp-prototype#10]
Methods should:
- Read database into marker class
- Read database into binned data classes

**Comment by grumpman** [comment]
Functions and logic for loading in the test data, marker classes and the binned classes have been implemented and store din global variables for use of other team members. Data is currently being loaded from a text file, this will need to be changed so it loads the data from the database. Other than that the algorithm implement works as intended (as far as I can tell). The main function to use will be loadNewTest(<test id>).

**Comment by hannahb1024** [comment]
Can confirm Sam has carried this out as can be seen in linked pull request.
