### ISSUE TITLE
Populate Tables With Example Data

### ISSUE THREAD

**Issue by hannahb1024** [hannahb1024/uob-sepp-prototype#3]
Populate tables with:
- Test data for previous students
- Example data for markers

Before deployment to a docker container, upload CSVs for simplicity.

**Comment by SamHarS** [comment]
I have added data to both of these tables.
I did this by:
- Making scripts to generate data, using binomial, normal and random distributions for the results table and the faker python library for the marker table
- I made the scripts write into a text file so the data was access able to other colleagues whilst I try and containerize the database
- I copied the data from the text files into my local postgres database
