### ISSUE TITLE
Construct Containerised SQL Database

### ISSUE THREAD

**Issue by hannahb1024** [hannahb1024/uob-sepp-prototype#5]
Put SQL database with example data in a docker container ready to be deployed to the development server

**Comment by SamHarS** [comment]
I have successfully containerised the database (with a lot of trial and error). I will need a key to have it as a package for this repo, but it has successfully been uploaded to my own account and publicised in the meantime.

**Comment by hannahb1024** [comment]
Database is available and running in a container on development server - IP is in discord server
