### ISSUE TITLE
Implement "Load Graph" Function

### ISSUE THREAD

**Issue by hannahb1024** [hannahb1024/uob-sepp-prototype#7]
Function should:
- Return suitable qt graph object
- Interface with statistical tests
- Interface with database to write changes to marker score

**Comment by hasbenton** [comment]
Graph now loads and generates the correct card object for the rest of the ui to display
utilises data from the statistical tests to display correctly

**Comment by hannahb1024** [comment]
Can confirm all works and interfaces - very pretty!
