### ISSUE TITLE
Create Chi-Squared Test Method

### ISSUE THREAD

**Issue by hannahb1024** [hannahb1024/uob-sepp-prototype#9]
Method should:
- Generate appropriate values for contingency table
- Calculate appropriate degrees of freedom
- Measure against p-values to determine confidence in marking
- Implement a method returning chi-squared value given binned values

**Comment by grumpman** [comment]
The chi-squared test has been implemented in the binned_data class, a get confidence function has been added to the marker class and functions have been created to automatically run the chi-squared test for each marker. Currently the contingency table and appropriate degrees of freedom are stored in a default list - will implement this soon.

**Comment by grumpman** [comment]
After further research into calculating values in the contingency table it has become clear that the algorithm to do so is extremely complex (see https://en.wikipedia.org/wiki/Chi-squared_distribution and https://en.wikipedia.org/wiki/Gamma_function) for a feature that is not required for the prototype as we will be sticking to 10 degrees of freedom for testing and evaluation. 
As a result I have resolved to simply make the critical values more accurate and to not add any redundant code to the program. With this implemented this part of the program will be completed.
